---
- name: web-server configuration
  hosts: build
  become: yes

  roles:
    - common
    - buildserver


- name: webappserver configuration
  hosts: web
  become: yes

  roles:
    - common
    - webappserver
